### PR TITLE
[GUI-47-2] Charts' dependency issue @ CI.

### PR DESCRIPTION
**Pull request by AndreyKoltsov1997**
**Now**: Since Darzee's Web UI, as an Angular app, doesn't get builded correctly, the UI is not accessible while running the docker image.
**Then**: Docker image's directory should be changed.

### CODE REVIEW

**Comment by AndreyKoltsov1997** [comment]
The problem was not with the application build itself, but with the ng2-charts dependency. Fixing it now.

**Comment by AndreyKoltsov1997** [comment]
See https://github.com/valor-software/ng2-charts/issues/750 for details.

**Comment by AndreyKoltsov1997** [comment]
In order to build a working image via Gitlab CI, as I've found out for 06.08.2019, it's advisable to: 
- Use Angular 7 builder; 
- Use ng2-charts 2.2.5; 
As a result, **I've froze Angular Core to 7.2.15, Angular CLI to 7.3.8, ng2-charts to 2.2.5**. The image works correctly with this set up.

**Comment by ACBNair** [comment]
@AndreyKoltsov1997 I think you are right. ng2-charts 2.2.5 Solved my issue.

**Pull request merged**
